### ISSUE TITLE
Thắc mắc :)

### ISSUE THREAD

**Issue by tienthanhjlw** [ehkoo/web#3]
Chào mọi người, em đang học Angular mình thắc mắc Blog có đề cập về các nội dung liên quan đến Angular không? Em cũng muốn tham gia làm cộng tác viên để vừa ôn tập lại kiến thức của chính mình  và có cơ hội được học hỏi thêm từ mọi người. :)

**Comment by kcjpop** [comment]
Chào Thành :wave:,

Hiện Ehkoo đang tập trung vào React với Vue á, bên cạnh JavaScript thuần. Cũng muốn lấn sang các công nghệ khác như Angular nhưng đó không phải là trọng tâm lắm. Một phần là trong team không có ai có kinh nghiệm về Angular để kiểm tra bài nữa.

Tuy vậy mình cũng rất hoan nghênh những bài tutorial dành cho những người mới bắt đầu á : )
